const PAGE = 'PAGE';
const SOLO_PAGE = 'SOLO_PAGE';
const TOPIC_PAGE = 'TOPIC_PAGE';
const CHAPTER_PAGE = 'CHAPTER_PAGE';
const CARD_PAGE = 'CARD_PAGE';
const MODAL_PAGE = 'MODAL_PAGE';
const QUESTION_PAGE = 'QUESTION_PAGE';
const PAGE_ARRAY = [ SOLO_PAGE, TOPIC_PAGE, CHAPTER_PAGE, CARD_PAGE, MODAL_PAGE, QUESTION_PAGE ];

module.exports = {
	PAGE,
	SOLO_PAGE,
	TOPIC_PAGE,
	CHAPTER_PAGE,
	CARD_PAGE,
	MODAL_PAGE,
	QUESTION_PAGE,
	PAGE_ARRAY
};
